services:
  docker-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-manager
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - KUBERNETES_API_SERVER=${KUBERNETES_API_SERVER}
      - KUBERNETES_TOKEN=${KUBERNETES_TOKEN}
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"